### ISSUE TITLE
Feature: Integrate Calendar with Tabs

### ISSUE THREAD

**Issue by DaPhysikist** [cse110-sp24-group26/final-project#64]
# Summary of feature

Upon clicking on a date on the calendar, a new tab should open with the entry for that respective date

# Expected difficulties

- Learning how to use the event functions
- Getting tabs to open smoothly

# Reference/example of similar feature from another app

Google calendar switches to the respective week when a date is clicked, this is similar

**Comment by enigmurl** [comment]
Fixed by #70
