### ISSUE TITLE
Testing: Tag Component Testing

### ISSUE THREAD

**Issue by AAvanzado** [cse110-sp24-group26/final-project#82]
# Type of testing
Component testing
# Affected modules
Tag section of the sidebar of the application
# Example test cases
- check that all tags initially unselected for any given day
- single click on tags to toggle
- right click for tag renaming ( then check if renaming is constant across different days )
- tag selection should be saved when revisiting a given day ( each day should have its own set of active/inactive tags )

**Comment by enigmurl** [comment]
Fixed by #101
